### PR TITLE
Auth plugin fixes

### LINKED ISSUE #99: Changing roles for user shows the user as "pending approval" until refresh
**Describe the bug**
Changing roles for user shows the user as "pending approval" until refresh

**To Reproduce**
1. Go to 'Team page
2. Update roles for user

==> The roles are modified BUT User last login switches to "pending approval"

**Expected behavior**
Only the roles should change

### LINKED ISSUE #101: [BUG] Removing role for a user which has 1 role does not work
**Describe the bug**
In case a user has 1 role, and I revoke this role from him - I get him as "pending approval" (I saw the other issue), however, the role does not get deleted.

**To Reproduce**
1. Go to team management
2. Click on a user with 1 role
3. Remove this error

**Expected behavior**
The role should be revoked.

**Additional context**
frontegg-react 1.6.0

### LINKED ISSUE #103: [BUG] - Integrating with <React.StrictMode> causes each URL to be loaded twice
**Describe the bug**
Integrating FronteggProvider with <React.StrictMode> causes each request to be sent twice

**To Reproduce**
1. Wrap your react application with <React.StrictMode>
2. Refresh
==> Each request from frontegg to the backend is sent twice

**Expected behavior**
The request should be sent only once

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by frontegg-david**
- feature: redirect user to login with two-factor after saml if required
- fix: multiple store initialization in strict-mode
- fix: remove last role in TeamTable
- fix: remain user data after editing roles in TeamTable

Resolves #99, resolves #101, resolves #103

### CODE REVIEW

File: packages/auth/src/Api/TeamState/saga.ts [hunk 1]
```diff
@@ -94,27 +81,39 @@ function* updateUser({ payload }: PayloadAction<WithCallback<IUpdateUser, ITeamU
...
         if (user.id === body.id) {
-          oldUserData = { ...user };
           return { ...user, ...body };
         }
         return user;
       }),
     })
   );
   try {
+    if (oldUserData.roleIds.length > 0 && body.roleIds?.length === 0) {
```
Comment (frontegg-david) [inline packages/auth/src/Api/TeamState/saga.ts:99]: this fix works, it will remove the last roleId from the current user

**Review by aviadmizrachi — APPROVED** [review]
